version: 1.0.{build}
image:
  - Ubuntu

environment:
  AWS_DEFAULT_REGION: us-west-2
  SAM_CLI_DEV: 1

  matrix:

    - PYTHON_VERSION: '3.7.4'
      PYTHON_ARCH: '64'
      RUN_SMOKE: 1
      NOSE_PARAMETERIZED_NO_WARN: 1
      INSTALL_PY_36_PIP: 1
      INSTALL_PY_38_PIP: 1

for:
  -
    matrix:
      only:
        - image: Ubuntu

    install:
      # Install AWS CLI
      - sh: "source ${HOME}/venv${PYTHON_VERSION}/bin/activate"
      - sh: "virtualenv aws_cli"
      - sh: "./aws_cli/bin/python -m pip install awscli"
      - sh: "PATH=$(echo $PWD'/aws_cli/bin'):$PATH"

      - sh: "which python"
      - sh: "which pip"
      - sh: "echo $PATH"

      - sh: "sudo apt-get -y install python3-distutils"

    build_script:
      - "python -c \"import sys; print(sys.executable)\""
      - "pip install -e \".[dev]\""

    test_script:
#      - sh: "python --version"
#      - sh: "which python"
#      - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -


      - sh: "pytest -vv tests/integration/buildcmd"
      - sh: "pytest -vv tests/integration/init/schemas"
